required = [
  "github.com/golang/lint/golint",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/briandowns/spinner"
  version = "1.6.0"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.3.5"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.3"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.1.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"
