name: Lint Markdown Links
run-name: ${{github.event.pull_request.title}}

on:
  pull_request:
  schedule:
    # Run every day at 5:00 AM
    - cron: "0 5 * * *"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
          config-file: '.mlc.config.json'
          folder-path: '.'
          max-depth: -1
          check-modified-files-only: 'yes'
          base-branch: 'release-2.20'
