name: TestSuite E2E

on:
  push:
    branches:
      - main
      - 'release-**'
  pull_request:
    branches:
      - main
      - 'release-**'
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**.go'
jobs:
  e2e-tests:
    name: "Run E2E tests"
    runs-on: ubuntu-latest
    env:
      K3D_VERSION: v5.4.7
    steps:
      - name: Checkout Kyma CLI
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        id: install
      - name: Build Kyma CLI
        run: | 
          make resolve validate build-linux
          chmod +x ./bin/kyma-linux
          ls -la ./bin
          mv ./bin/kyma-linux /usr/local/bin/kyma
        timeout-minutes: 10
      - name: Set up k3d
        run: wget -qO - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=$K3D_VERSION bash
      - name: Run Provision
        run: |
          ls -la /usr/local/bin
          kyma --ci provision k3d \
            -p 8083:80@loadbalancer \
            -p 8443:443@loadbalancer \
            --timeout 1m \
            --k3d-arg --no-rollback \
            --name kyma
      - name: Update Kubeconfigs
        run: k3d kubeconfig merge -a -d
      - name: Run E2E tests
        run: make -C tests/e2e test-module-enabling-disabling